# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170605_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
