# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170606_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
